name: Deploy Docs WebSite

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: web-site/pnpm-lock.yaml
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: web-site

      - name: Build project
        run: pnpm run build
        working-directory: web-site

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:owner/repo.git
          BRANCH: main
          FOLDER: web-site/dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_DOCS_PRIVATE_KEY }}